name: travelmate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.1.0
  google_sign_in: ^6.2.1  
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  geocoding: ^4.0.0
  latlong2: ^0.9.1
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  provider: ^6.0.0
  cloudinary_public: ^0.23.1
  gal: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/map_data.json
    - assets/images/
    - assets/images/tourist_spots/
    - assets/images/hotels/
    - assets/images/placeholder.jpg
    - assets/images/london.jpg
    - assets/images/new_york.jpg